### ISSUE TITLE
[1.49] App crashes after finishing a new endless level

### ISSUE THREAD

**Issue by carlosjeurissen** [ochadenas/cpudefense#193]
After finishing a new level in endless mode, the app crashes. It does store the fact it finished the level. With sometimes storing the collected coins while other times not storing the collected coins.

**Comment by carlosjeurissen** [comment]
@ochadenas This seems to be resolved in v1.50.

**Comment by carlosjeurissen** [comment]
This also happens in v1.51. Updated the title to reflect this.

**Comment by brezelman** [comment]
This seems to be the bug I got. Here's the stacktrace:

> FATAL EXCEPTION: DefaultDispatcher-worker-6
Process: de.chadenas.cpudefense, PID: 4929
java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1220)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1186)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1134)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1093)
	at com.example.cpudefense.Intermezzo$HeroSelection.createBitmap(Intermezzo.kt:421)
	at com.example.cpudefense.Intermezzo$HeroSelection.prepareScreen(Intermezzo.kt:414)
	at com.example.cpudefense.Intermezzo.fadeDone(Intermezzo.kt:74)
	at com.example.cpudefense.effects.Fader.endFade(Fader.kt:45)
	at com.example.cpudefense.effects.Fader.update(Fader.kt:74)
	at com.example.cpudefense.GameView.updateEffects(GameView.kt:347)
	at com.example.cpudefense.activities.GameActivity.updateGraphicalEffects(GameActivity.kt:602)
	at com.example.cpudefense.activities.GameActivity.access$updateGraphicalEffects(GameActivity.kt:43)
	at com.example.cpudefense.activities.GameActivity$updateGraphicalEffects$1.invokeSuspend(GameActivity.kt:604)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:832)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@bf18a10, Dispatchers.Default]

**Comment by Tinsus** [comment]
Same with me in v 1.61

````
type: crash
osVersion: google/stallion/stallion:17/CP2A.260605.012/2026062801:user/release-keys
userType: full.secondary
flags: dev options enabled
package: de.chadenas.cpudefense:61, targetSdk 36
process: de.chadenas.cpudefense
processUptime: 92724 + 449 ms

java.lang.IllegalArgumentException: width and height must be > 0
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1425)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1391)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1339)
	at android.graphics.Bitmap.createBitmap(Bitmap.java:1298)
	at com.example.cpudefense.Intermezzo$HeroSelection.createBitmap(Intermezzo.kt:445)
	at com.example.cpudefense.Intermezzo$HeroSelection.prepareScreen(Intermezzo.kt:438)
	at com.example.cpudefense.Intermezzo.fadeDone(Intermezzo.kt:75)
	at com.example.cpudefense.effects.Fader.endFade(Fader.kt:45)
	at com.example.cpudefense.effects.Fader.update(Fader.kt:74)
	at com.example.cpudefense.GameView.updateEffects(GameView.kt:411)
	at com.example.cpudefense.activities.GameActivity.updateGraphicalEffects(GameActivity.kt:684)
	at com.example.cpudefense.activities.GameActivity.access$updateGraphicalEffects(GameActivity.kt:52)
	at com.example.cpudefense.activities.GameActivity$updateGraphicalEffects$1.invokeSuspend(GameActivity.kt:686)
	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:101)
	at kotlinx.coroutines.scheduling.CoroutineScheduler.runSafely(CoroutineScheduler.kt:589)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.executeTask(CoroutineScheduler.kt:832)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.runWorker(CoroutineScheduler.kt:720)
	at kotlinx.coroutines.scheduling.CoroutineScheduler$Worker.run(CoroutineScheduler.kt:707)
	Suppressed: kotlinx.coroutines.internal.DiagnosticCoroutineContextException: [StandaloneCoroutine{Cancelling}@c2f46f7, Dispatchers.Default]
```
`

**Comment by carlosjeurissen** [comment]
This can still be reproduced in v1.63.
