### ISSUE TITLE
OutOfMemoryError when loading background images

### ISSUE THREAD

**Issue by agateau** [ochadenas/cpudefense#27]
Thanks for the game, I love it!

Works great on my phone, but it crashes on my son phone, which is a Moto G4 plus. Looking at the logcat, I see it crashes with an OutOfMemoryError while trying to load the background images. Here is the stacktrace:

```
E  java.lang.OutOfMemoryError: Failed to allocate a 128990748 byte allocation with 16777216 free bytes and 63MB until OOM
at dalvik.system.VMRuntime.newNonMovableArray(Native Method)
at android.graphics.BitmapFactory.nativeDecodeAsset(Native Method)
at android.graphics.BitmapFactory.decodeStream(BitmapFactory.java:620)
at android.graphics.BitmapFactory.decodeResourceStream(BitmapFactory.java:455)
at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:478)
at android.graphics.BitmapFactory.decodeResource(BitmapFactory.java:508)
at com.example.cpudefense.effects.Background.loadBitmaps(Background.kt:40)
at com.example.cpudefense.effects.Background.choose(Background.kt:60)
at com.example.cpudefense.Game.startNextStage(Game.kt:338)
at com.example.cpudefense.Intermezzo.onDown(Intermezzo.kt:156)
at com.example.cpudefense.Game.onDown(Game.kt:236)
at com.example.cpudefense.GameView.onDown(GameView.kt:100)
at android.view.GestureDetector.onTouchEvent(GestureDetector.java:590)
at androidx.core.view.GestureDetectorCompat$GestureDetectorCompatImplJellybeanMr2.onTouchEvent(GestureDetectorCompat.java:480)
at androidx.core.view.GestureDetectorCompat.onTouchEvent(GestureDetectorCompat.java:543)
at com.example.cpudefense.GameView.onTouchEvent(GameView.kt:95)
at android.view.View.dispatchTouchEvent(View.java:9942)
```

We can workaround the crash by disabling the background, but it would be nice if the game handled this more gracefully, by either loading a smaller version of the background image, or loading only the image to display.

Thanks again for the game!

**Comment by ochadenas** [comment]
Tried to handle this. However, I'm not sure whether this was successful.

The problem is, I'm not able to reproduce the OutOfMemoryError. If I provoke an Out Of Memory Error, the thread just crashes without notice, which makes it impossible to react to this problem.

But try with version 1.16 whether there is  any amelioration.
